---
# tasks file for babu.mysql
- name: Download MySQL Community Repo
  get_url: url=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm dest=/tmp mode=0644
- name: Install MySQL Community Repo
  yum: name=/tmp/mysql-community-release-el7-7.noarch.rpm state=present
- name: Install MySQL Server
  yum: name="{{ item }}" state=present
  with_items:
      - mysql-server
      - MySQL-python
- name: Start MySQL Server and enable it
  service: name=mysqld state=started enabled=yes
- name: Change root password
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
      - "{{ db_host }}"
      - 127.0.0.1
      - ::1
      - localhost

- name: store mysql root password
  copy: src=mysql.cnf dest=/root/.my.cnf mode=0644
- name: create database
  mysql_db: name="{{ db_name }}" state=present
- name: create user
  mysql_user: name="{{ db_user_name }}" password="{{ db_user_pass }}" priv=*.*:ALL host="{{ db_host }}" state=present
- name: copy the sql file
  copy: src=locations.sql dest=/tmp mode=0644
- name: Import DB
  mysql_db: name=tourguide target=/tmp/locations.sql state=import
- name: Start MySQL Server and enable it
  service: name=mysqld state=started enabled=yes
 
